name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Lint (optional)
        run: |
          if [ -f package.json ] && grep -q 'lint' package.json; then
            npm run lint || echo "Lint warnings found"
          fi

      - name: Run Tests
        run: npm test

      - name: Upload Test Results (optional)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: coverage/
